### ISSUE TITLE
New tags ar not added to feeds

### ISSUE THREAD

**Issue by clearmisp** [remyhonig/elfeed-org#46] opened 2018-03-01 14:21 UTC
I have my feeds organized like the following in elfeed.org:

```
* Blogs                                        :elfeed:

** Nightly Builds
*** http://bobby.clearit.se:8080/jenkins/job/scm/rssAll  :jenkins:

** Emacs                                           :emacs:
*** http://planet.emacsen.org/atom.xml
*** https://stackoverflow.com/feeds/tag/emacs
*** https://www.masteringemacs.org/feed
*** http://endlessparentheses.com/atom.xml
*** https://oremacs.com/
*** http://pragmaticemacs.com/feed/

** C++                                             :cpp:
*** [[https://arne-mertz.de/feed/][Simplify C++]]
*** https://isocpp.org/blog/rss/category/news
*** https://www.fluentcpp.com/feed/
```

I then add a "stack" tag to the stackoverflow feed:

```
* Blogs                                        :elfeed:

** Nightly Builds
*** http://bobby.clearit.se:8080/jenkins/job/scm/rssAll  :jenkins:

** Emacs                                           :emacs:
*** http://planet.emacsen.org/atom.xml
*** https://stackoverflow.com/feeds/tag/emacs      :stack:
*** https://www.masteringemacs.org/feed
*** http://endlessparentheses.com/atom.xml
*** https://oremacs.com/
*** http://pragmaticemacs.com/feed/

** C++                                             :cpp:
*** [[https://arne-mertz.de/feed/][Simplify C++]]
*** https://isocpp.org/blog/rss/category/news
*** https://www.fluentcpp.com/feed/
``` 

Restarting Emacs and then doing M-x elfeed has no effect, the new "stack" tag does not show up. Is this a bug or am I doing something wrong?

**Comment by Eoksni** [comment] 2018-04-02 21:14
I also experience this issue, although I originally had no tags at all in my org file, so after using elfeed for a while I tried to add some tags, and no tags appear in the elfeed search buffer.

**Comment by gonhen** [comment] 2018-05-12 09:14
I also have the same problem. Any solution?

**Comment by Eoksni** [comment] 2018-05-13 03:45
@gonhen It seems that new tag settings do no apply retroactively, in other words, they apply only for the entries that will be fetched from now on.

**Comment by remyhonig** [comment] 2019-01-07 11:44
A workaround: you can empty your elfeed database and refetch all posts. Only then will the posts be tagged with the changed settings. Be advised that you might loose older posts that are not available in the rss feeds anymore.

I'm closing this as this is not a bug but more of a feature request.

**Closed by remyhonig** 2019-01-07 11:44 UTC

**Comment by henningninneh** [comment] 2023-01-17 10:28
If I invoke elfeed-update, the feed contents are updated, but not the tags. Only newly added feeds will show tags. But perhaps you mean something else by "empty your elfeed database and refetch"?
